name: pg_tuna

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        pip install -e ".[tests]"
    - name: Test with flake8
      run: |
        flake8 tests src
    - name: Test with pytest
      run: |
        pytest tests --cov src --cov-report term --cov-report html
    # - name: Report coverage
    #   run: |
    #     codecov
